FROM ubuntu:latest

RUN apt-get update
RUN apt-get install -y --no-install-recommends tzdata g++ curl

RUN apt-get update
RUN apt-get install -y openjdk-11-jdk
ENV JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"

FROM python:3.8

WORKDIR /app/

COPY ./main.py /app/
COPY ./requirements.txt /app/

RUN pip install -r requirements.txt

EXPOSE 8000

CMD uvicorn --host=0.0.0.0 --port 8000 main:app