FROM ubuntu

RUN apt-get update

RUN apt-get install -y openjdk-11-jdk

FROM python:3.8

WORKDIR /app/

COPY ./main.py /app/
COPY ./requirements.txt /app/

RUN pip install -r requirements.txt

EXPOSE 8000

CMD uvicorn --host=0.0.0.0 --port 8000 main:app